# Generated by Django 2.0.4 on 2018-04-14 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartfridge', '0003_auto_20180414_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_model', to=settings.AUTH_USER_MODEL),
        ),
    ]
