# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-15 22:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartfridge', '0004_auto_20180414_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_model', to=settings.AUTH_USER_MODEL),
        ),
    ]
